### ISSUE TITLE
Share does not show Account

### ISSUE THREAD

**Issue by mwlczk** [tigase/siskin-im#109]
**Describe the bug**
I want to share out of another App via Siskin. But the share "ViewComponent" would not show any account

**To Reproduce**
see above

**Expected behavior**
I can choose an account and the contacts I want to share to.

**Screenshots**
can add later.

**Details (please complete the following information):**
 - Siskin Version: [6.4]
 - iOS version [14.4]
 - iPhone model [iPhone 6s]

**Additional context**

**Comment by hantu85** [comment]
In the latest build in TestFlight sharing functionality was reimplemented. This should no longer be an issue.

**Comment by mwlczk** [comment]
sharing is possible again. 
though only unencrypted and 1:1 chats only

**Comment by ltGuillaume** [comment]
@mwlczk Why only unencrypted?

**Comment by mwlczk** [comment]
> @mwlczk Why only unencrypted?

@ltGuillaume, if you share out of an other app to Siskin, than the message is not being encrypted.
Only if you share from within Siskin.

**Comment by ltGuillaume** [comment]
Why would that make sense in any way? It quite misleading if there's no warning beforehand, too.

**Comment by hantu85** [comment]
@ltGuillaume Siskin IM is an XMPP client. OMEMO is one of the features of the XMPP protocol and while it is supported in the main app, it is not in the extension which is used for sharing. This is caused by the difficulties enforced by the iOS requirements and as sharing extension is not the main functionality of the app, it lacks support for OMEMO encryption.

The OMEMO support for sharing extension will be added in the future.

**Comment by ltGuillaume** [comment]
I don't have experience with developing for iOS, but it seems that opening the main app from a (sharing) extension is easily possible, which would make it easy to use the main app's OMEMO encryption, too.

Example: https://scribe.nixnet.services/@damisipikuda/how-to-receive-a-shared-content-in-an-ios-application-4d5964229701
