### ISSUE TITLE
Push notification not received

### ISSUE THREAD

**Issue by Tuxicoman2** [tigase/siskin-im#133]
Hi,
While Siskin client is disconnected from the server (iPhone app is closed since a few seconds and the server log tells that it registered the client disconnected), someone sends a message (from Conversations on Android). The server (Prosody 0.11.9) seems to handle the push (I use the https://hg.prosody.im/prosody-modules/file/tip/mod_cloud_notify/mod_cloud_notify.lua at rev 6e5572fc6840 ) . See below :

Aug 27 20:55:37 s2sout5557c686f770	info	Stream encrypted (TLSv1.3 with TLS_AES_256_GCM_SHA384)
Aug 27 20:55:37 s2sout5557c686f770	info	Outgoing s2s connection jesuislibre.net->push.tigase.im complete
Aug 27 20:55:41 s2sin5557c64572c0	info	Stream encrypted (TLSv1.3 with TLS_AES_256_GCM_SHA384)
Aug 27 20:55:41 jesuislibre.net:saslauth	info	Accepting SASL EXTERNAL identity from push.tigase.im
Aug 27 20:55:41 s2sin5557c64572c0	info	Incoming s2s connection push.tigase.im->jesuislibre.net complete

**Expected behavior**
A notification should appear on the iOS device to show to the user he receives a message.

**Details (please complete the following information):**
 - Siskin Version: 6.4
 - Iphone 11
 - iOS version 14

**Comment by hantu85** [comment]
A few additional questions:
1. Was this OMEMO encrypted message?
2. Did you have any other notifications from SiskinIM pending?

I've checked push component logs and there is no error.

Please keep in mind that we are forced to use APNS for push notifications delivery and it is done by APNS on "best effort" basis, which means APNS can drop notifications as well (due to some rules or errors), even without returning an error back to us.

**Comment by Tuxicoman2** [comment]
Hi.

It seems to work today (same config as in the report).

**Comment by Tuxicoman2** [comment]
I seems what solved it is the update of the https://hg.prosody.im/prosody-modules/file/tip/mod_cloud_notify/mod_cloud_notify.lua
The current version bundled in Debian 11 (bullseye) is too old.
