### ISSUE TITLE
default settings questions

### ISSUE THREAD

**Issue by theotheroracle** [tigase/siskin-im#202]
**Is your feature request related to a problem? Please describe.**
encryption is not enabled by default, and it is not clear when you are sending plaintext .

emotions are rendered as emoji by default, which is very confusing and leads to not under-standing why someone is communicating in a style not typical with their usual state, it was alarming .  also, why is this in experimental settings ?
 
**Describe the solution you'd like**
defaults should be changed, encryption should be more clear, and the emoticon should be moved out of experimental and renamed to something more appropriate, or perhaps removed altogether . most chat apps have a feature which does this for out going messages but not obscuring what is written . also don't enable it by default, *please*

**Describe alternatives you've considered**
for encryption for example, changing the colour of unencrypted messages, or maybe a symbol to show they are unencrypted

**Comment by hantu85** [comment]
Those `poor default settings` are there by design and were chosen intentionally and are poor in your opinion and not mine.

> encryption is not enabled by default, and it is not clear when you are sending plaintext .

Encryption is not enabled by default as it is not supported by all XMPP clients and in my tests, there were issues with OMEMO (but those were solved). However, losing previous messages exchanged in the conversation, which you will if you will use a new XMPP client or a new device if messages were sent with OMEMO encryption thanks to perfect forward secrecy, is in my opinion more problematic than adjusting the encryption setting acknowledging that you know and understand what you are doing.

> motions are rendered as emoji by default, which is very confusing and leads to not under-standing why someone is communicating in a style not typical with their usual state, it was alarming . also, why is this in experimental settings ?

It was added as an experimental option (enabled by default) a very long time ago and that behavior was intended. You have the option to disable it to adjust Siskin to what you expect from your client.

> for encryption for example, changing the colour of unencrypted messages, or maybe a symbol to show they are unencrypted

There is an icon (lock) that states which messages were encrypted. There is also a lock by the contact name in the top bar notifying you that message will be encrypted. I'm strongly against adding colors to distinct encrypted messages (or unencrypted) as this will also be meaningless for anyone not understanding their meaning. Adding additional icons will create only more clutter on the already "busy" screen of the phone.

**Comment by theotheroracle** [comment]
experimental features shouldn't be enabled by default, also, its very jarring behaviour . it is unlike any other client, so this behaviour is unexpected, but also not knowing if your message has sent as an emoticon or an emoji is an important distinction, or how others have sent their messages is also strongly comfusing, as they are tonally  different . 

also, having a lock or unlock icon is not more cluttered than only showing a lock icon when the chat is encrypted . i understand not wanting different colors, that's fine, but heaviness things be more clear is important, for privacy reasons . 

i can also understand not enabling encryption by default for client compatibility in new rooms, but if there is already omemo fingerprints in the room, or encrypted messages, it doesn't make sense to send plain text

**Comment by theotheroracle** [comment]
i installed siskin on another device and found the option (show emissions) wasn't enabled, seems i may have enabled it by mistake not knowing, if so, i'm very sorry for the misunderstanding, and instead i'd only recommend changing the name of the setting to something like "replace emoticons" so it's more clear what it does

**Comment by hantu85** [comment]
> also, not knowing if your message has sent as an emoticon or an emoji is an important distinction

Your message is not being modified when it is sent. Only the presentation is changed and you can, using setting in the client, adjust it to your taste.

> i can also understand not enabling encryption by default for client compatibility in new rooms, but if there is already omemo fingerprints in the room, or encrypted messages, it doesn't make sense to send plain text

For easier-to-understand behavior, in the client, you can configure if encryption is enabled or not. If that behaviour would be changing from conversation to conversation, as you are suggesting, it would be inconsistent and more difficult to understand to the users.

Thank you for your comments and opinions. We will consider them when we will for on future version of the app.

**Comment by theotheroracle** [comment]
apologies for the original tone
