### ISSUE TITLE
Notification counter are not synced between devices

### ISSUE THREAD

**Issue by jnaeff** [tigase/siskin-im#27]
**Is your feature request related to a problem? Please describe.**
I use both BeagleIM and SiskimIM. If I read my message for example on BeagleIM then my message counter goes nice to zero if I read all the messages. But my message counter on SiskimIM is then not updated. 

**Describe the solution you'd like**
Is it possible to sync the unread message counter between BeagleIM and SiskimIM. I don't know if this is possible with the current XEP's.

**Comment by hantu85** [comment]
Currently this is already supported but it depends on the support on the server side. Right now it works correctly with Tigase and I’m not aware of any other server sending push notification from the server where offline messages are retrieved by another client.

Due to that I’m closing this task as feature exists and is working just fine.
