### ISSUE TITLE
siskin does not register

### ISSUE THREAD

**Issue by qvqc** [tigase/siskin-im#31]
New siskin installation will not register with desired server.

I installed siskin, and then attempted to register account on well known compliant server.  App fails saying server can not be found.

I expected siskin to register on the desired server.

**Comment by hantu85** [comment]
In our testing, SiskinIM was able to connect to all servers against it was tested.

Without knowing on which server you were trying to register it will not be possible to solve this issue.

If app says that the server can not be found it means that it was not possible to connect to that server, either due to DNS issues or networking issues.

**Comment by qvqc** [comment]
Ejabberd. 

 The server has compliance @ 94%.  though Its missing (XEP-0215: External Service Discovery (STUN) , XEP-0215: External Service Discovery (TURN) , and XEP-0156: Discovering Alternative XMPP Connection Methods (HTTP) .  

It works as expected with gajim, conversations, conversejs, and dino.

**Comment by hantu85** [comment]
I can confirm that Siskin is able to connect and register to local ejabberd used for testing.

**Comment by qvqc** [comment]
Thanks, I will try and register on a different iOS device.  I am not that familiar with the system, maybe something blocked siskins connection.

**Comment by qvqc** [comment]
Tested with other servers and had success.  Strange as all other xmpp clients I try work with original server.  Closing for now as I dont understand what is wrong with my ejabberd that siskin wont see it.
