### ISSUE TITLE
Module 'TigaseSwift' was created for incompatible target x86_64-apple-macos10.11

### ISSUE THREAD

**Issue by NagarajuMetavoxx** [tigase/siskin-im#33]
Hello,

I've downloaded the project from github and trying to run the code.

I'm getting these error `No such module 'TigaseSwift'` . then I downloaded the TigaseSwift framework from this link(https://github.com/tigase/tigase-swift) and added the project. Now I'm getting below error.

`/Users/raju/Documents/siskin-im-master/SiskinIM/vcard/VCardEditAddressTableViewCell.swift:23:8: Module 'TigaseSwift' was created for incompatible target x86_64-apple-macos10.11: /Users/raju/Documents/siskin-im-master/TigaseSwift.framework/Modules/TigaseSwift.swiftmodule/x86_64.swiftmodule`

Thanks

**Comment by hantu85** [comment]
I suppose that you are using code from `master` branch. For easier compilation please use code from `mix` branch as it contains proper configuration for SwiftPM and will properly download code and compile TigaseSwift for proper architecture.

This error means that XCode in your case compiled TigaseSwift for macOS not for iOS.

**Comment by f055** [comment]
Does the changes in the `mix` branch mean it's possible to compile by simply opening the `SiskinIM.xcodeproj` or do we need to create a new workspace and add openssl, xmpp and omemo like before?

Also, SwiftPM seems to want to include `https://github.com/tigase/libsignal` but that repo is 404.

**Comment by hantu85** [comment]
There is still a need to add WebRTC and OpenSSL as SwiftPM does not allow (yet?) to depend on binaries and WebRTC and OpenSSL are huge and require a lot of time to compile.

TigaseSwift and TigaseSwiftOMEMO will be fetched by SwiftPM.

**Comment by f055** [comment]
Thanks @hantu85 for a superfast reply and fixing `libsignal`. I'll try further and see where it gets me. OpenSSL seem to have built fine, not sure about WebRTC as that didn't appear to be a dependancy error (yet?).

**Comment by f055** [comment]
By creating a new workspace and adding SiskinIM project using the `mix` branch, Xcode indeed pulled automatically TigaseSwiftOMEMO, TigaseSwiftFor and libsignal.

Then I've added OpenSSL and built it. Then I tried building the SiskinIM > Shared library and to make it successful I had to:
1. Shared > General > Frameworks and Libraries: remove openssl framework and add OpenSSL framework. Update the referenced code error, from `import openssl` to `import OpenSSL`.
2. Shared > Build Settings > Enable Bitcode: No.

Finally, I had to go back a few commits (to d747cdc) to remove code errors due to audio/video development. SiskinIM built successfully and launched in the Simulator.
