### ISSUE TITLE
6.0 no option to invite contacts to private group chat

### ISSUE THREAD

**Issue by joshimio** [tigase/siskin-im#57]
Hi. I can't find an option to invite participants to a private group chat on siskin 6.0 (iOS 12.4.8).

I can create a new MIX enabled MUC by:

+/New private group chat/[enter channel name]/Next/[enter nickname]/Create

but no other option to send out invites, even after that new private group chat has been created. If I've missed something, could someone point me in the right direction. Thanks.

**Comment by hantu85** [comment]
After creation of MIX channel and entering into it, you need to tap on "group of people" icon in the top right corner. Then you will see a list of participants which again in the top right corner will have a "+" icon allowing you to send invites.

**Comment by joshimio** [comment]
I can't see a "+" icon anywhere on the Participants screen. The list of participants just shows the account which created the group chat. Please see the pics attached.

![6f1cf39e_Kjv_OXRuRVWbVu5Qvc5t1w](https://user-images.githubusercontent.com/24639517/94371887-ad53ca00-00f1-11eb-967c-5a789edb51f1.jpg)
![cf0ddad4_u1Kqn_yNQ5mRRzrGs8h8jg](https://user-images.githubusercontent.com/24639517/94371888-adec6080-00f1-11eb-8ab2-73ebee63d95a.jpg)

**Comment by hantu85** [comment]
Have you created the MIX channel from the same account?

**Comment by joshimio** [comment]
Yes. aaliyah@sure.im is the account which created the group chat "leopard".

**Comment by hantu85** [comment]
I'll double-check how client behaves but as I've just checked, I do see a "+" icon (it loads after the participants list if refreshed)

**Comment by hantu85** [comment]
I've just checked with latest SiskinIM and the account at the sure.im and I do see a "+" icon.

The issue here is iOS 12.4.8 which you are using. We try to support older versions of iOS but we need to prioritize support for newer versions of iOS. Due to that MIX is supported on iOS 12 but currently there is no way to "manage" participants on this version of iOS. The support for that *may* be added in the next version, but as iOS 12 is 2 years old and any device with iOS 13 or newer already has this feature (which is over 81% of all Apple iOS based devices).

**Comment by joshimio** [comment]
Ok, thanks for checking.
