### ISSUE TITLE
MUC invites to Android/Conversations

### ISSUE THREAD

**Issue by joshimio** [tigase/siskin-im#65]
Sending MIX enabled MUC invite from Siskin/Beagle to contact using Conversations doesn't work for me.

When sending MUC invite from Beagle/Siskin to Beagle/Siskin, an Accept button appears with the link, allowing contact to join the chat. This Accept button is missing when inviting an Android contact on Conversations.

It is still possible for the Conversations contact to join the chat manually by copy/pasting the chat address.

Is this a problem on Beagle/Siskin end or Conversations?

ios 14.0.1/siskin im 6.0
macos: 10.15.7 catalina/beagle im: 4.0
conversations: 2.9.0+fcr

**Comment by hantu85** [comment]
You are not sending MUC invite but a MIX invite, that is why Conversations does not know what to do. Support for MUC in MIX is optional but Tigase MIX component supports that and thanks to that Conversations is capable of joining MIX channel using the address.

We could probably support sending both invites in this case, but other clients supporting MIX & MUC could end up showing doubled invites, due to that we are sending only MIX invite but sending channel address as a fallback.

**Comment by joshimio** [comment]
Thanks, makes sense.
