### ISSUE TITLE
pictures cut off at edges and receiver just gets push notification but message not displayed

### ISSUE THREAD

**Issue by onefreeworld** [tigase/siskin-im#72]
my device:
iphone SE 2020 version 14.2
siskin IM version 6.1 (last updated Nov 13 2020)
server: jabber.de running Prosody 0.11.7 (https://compliance.conversations.im/server/jabber.de/)
I am using siskin IM and Windows Gajim

Hi there,
I am just a simple user with not a lot knowledge about tech stuff, please let me know if you need more information :) (and sorry for my funny English)

I have two things to ask today:

- since the update last week pictures received on siskin IM got cut off at the edges a bit too much, some details are lost. Can I improve this somehow?

- my friend is using Androids Conversation (I don't know details of her device, but same server), they had an update few days earlier too, but she is certain since the update of siskin IM she receives messages send from my iPhone only as the push notification but cant see it in chat history. (I told her to ask the devs of conversation herself, just wanted to mention it here too, as it seems it does not happen if I send a message from Gajim to Conversations)

Thank you!

By the way: Great app! Best so far for iPhone (and I tried a few already)

Love from Germany
Choco

**Comment by hantu85** [comment]
> since the update last week pictures received on siskin IM got cut off at the edges a bit too much, some details are lost. Can I improve this somehow?

As far as I can tell, we have not changed how received pictures are downloaded and presented to the user. That was not changed and we relay on iOS LinkPreview functionality for "preview" generation. Most likely images in your case are either very tall or very wide. In those cases, borders may be cut out. This behaviour is intentional as very wide or very tall images would create bigger issues with displaying them (ie. taking all of the screen).  However, if you tap on that photo it will be shown at original aspect ratio (and will not be cut out).

> my friend is using Androids Conversation (I don't know details of her device, but same server), they had an update few days earlier too, but she is certain since the update of siskin IM she receives messages send from my iPhone only as the push notification but cant see it in chat history. (I told her to ask the devs of conversation herself, just wanted to mention it here too, as it seems it does not happen if I send a message from Gajim to Conversations)

I'm not aware of anything which could cause an issue like that. I suppose that if OMEMO was used then Siskin could not have a correct key for Conversation on her device and that resulted in sending a message not correctly encrypted for that device which lead to dropping of the message by Conversations.

**Comment by onefreeworld** [comment]
Hi there,
just about the pictures this time:

I don´t get it, what you mean with "tap on that photo it will be shown at original aspect ratio (and will not be cut out)." ? 
If I tap on a photo, the app offers me: "Open Link", "Copy Link" or "Share". 
If I tap on "open link" nothing happens.  
If I tap on "copy link" ... well what to do with it? copy and probably paste it to where? Clearly not to a browser as this does not open the picture.
If I tap on "share" I can safe the photo to my personal pictures app. Where I finally find the picture/photo in the correct size. But why so complicated? Why do I have to safe it at all? Sometimes friends send you stuff I just want to look at an laugh and forget about it again. Don't want to safe it in the pictures app.

Is it possible to open the photos/pictures just inside the siskin app without saving them first?

Thank you guys for your help! :)


I attached you what actually happens to a picture my friend just send me today. She took a screenshot with her phone. Yes it is a tall picture because it's a screenshot, but not extra tall. iPhone is usually able to display screenshots ;)

Fist picture what came through on siskin. Second picture what she actually sent me:

![screenshot 2](https://user-images.githubusercontent.com/44290360/104161968-07a03e80-53f4-11eb-942d-1dbedb13b6b4.PNG)
![screenshot](https://user-images.githubusercontent.com/44290360/104161973-0a029880-53f4-11eb-9810-42e38978ec6c.PNG)

**Comment by hantu85** [comment]
As I've mentioned before - that is a preview (created by Apple Framework).

As for tapping on the link, that should open it and it does for me, so I cannot tell what is wrong in your case.

**Comment by onefreeworld** [comment]
As I mentioned before, tapping on the picture does NOT open it in my case. Otherwise I would not ask.

And because you don't know you just close the case? Maybe somebody else has the same issue and would like to (get) help?

**Comment by hantu85** [comment]
Tapping on the picture does the same thing as holding on the "preview" and then using "Open..".

Unfortunately, Apple decided to stop opening images from those links breaking the app on iOS 14.x (I cannot confirm which version but that worked fine on iOS 13.x).

For now please use "Share" and save to see a full preview.

That "issue" will be most likely fixed in some future version.

**Comment by onefreeworld** [comment]
Well that's at least an answer: it worked on older iOS and will be fixed (most likely). 

Thank you! :)
